# Generated by Django 5.0.1 on 2024-01-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunaCiudadRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(choices=[('lo_barnechea', 'Lo Barnechea'), ('las_condes', 'Las Condes'), ('vitacura', 'Vitacura'), ('providencia', 'Providencia'), ('nunoa', 'Ñuñoa'), ('la_reina', 'La Reina'), ('penalolen', 'Peñalolen'), ('macul', 'Macul'), ('la_florida', 'La Florida'), ('puente_alto', 'Puente Alto'), ('recoleta', 'Recoleta')], max_length=100)),
                ('ciudad', models.CharField(choices=[('algarrobo', 'Algarrobo'), ('santiago', 'Santiago'), ('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('puerto_montt', 'Puerto Montt'), ('valdivia', 'Valdivia')], max_length=100)),
                ('region', models.CharField(choices=[('arrica_parinacota', 'Arrica Parinacota'), ('coquimbo', 'Coquimbo'), ('maule', 'Maule'), ('los_rios', 'Los Rios'), ('tarapaca', 'Tarapaca'), ('valparaiso', 'Valparaiso'), ('nuble', 'Ñuble'), ('los_lagos', 'Los Lagos'), ('metropolitana', 'Region Metropolitana'), ('bio_bio', 'Bio Bio'), ('aysen', 'Aysen'), ('araucania', 'Araucania')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('giroempresa', models.CharField(max_length=255)),
                ('telefonoempresa', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefonocliente', models.CharField(max_length=15)),
                ('comuna_ciudad_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comunaciudadregion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
            ],
        ),
    ]
